# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HAND DRIP
email: "dripserver@gmail.com"
description: ""
baseurl: "/lib" # The subpath of your site, e.g. /blog
favicon: "/images/favicon" # favicon
url: "https://handdrip.github.io" # The base hostname & protocol for your site
twitter: ""
github: "handdrip"
instagram: ""
facebook: ""
google_analytics: UA-153069100-1 # Google Analytics
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty
paginate: 10

sass:
  style: compressed

plugins:
  - jekyll-paginate

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

collections:
  lib_tags:
    output: true
    permalink: /tag/:name/
    filepath: /tags
    layout: tag_page
